[tool.black]
exclude = "venv"

# black compatible isort config
# from https://black.readthedocs.io/en/stable/the_black_code_style.html
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = "migrations,venv"
known_first_party = "api,bikesharing,cykel,eventphone_auth,gbfs,owncloud_auth"

# not yet there: https://gitlab.com/pycqa/flake8/-/issues/428
# look into the .flake8 file instead
# [tool.flake8]

# not yet there: https://github.com/pytest-dev/pytest/issues/1556
# look into the setup.cfg file instead
# [tool.pytest]
